### PR TITLE
Cleaning and fixes

### PR DESCRIPTION
**Pull request by SeaDve**
This should also remove some deprecated properties that should be remove before gtk4 porting

### CODE REVIEW

**Review by tim77 — CHANGES_REQUESTED** [review]
Please drop `shared-modules` from 6a6bfb5935669a7f045ae626148c3aee57b21c8e. Otherwise LGTM.

**Comment by SeaDve** [comment]
huh, for some reason it is still there, even though I didn't staged it

**Comment by tim77** [comment]
Also need to squash couple commits, not all. I will rebase it manually, don't worries about this. Thank you as always.

**Comment by SeaDve** [comment]
Thanks! Also, you're welcome.

**Pull request closed without merging**
