### PR TITLE
Icons Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icon isn't even on SVG and is unnecessarily complicated.

### CODE REVIEW

**Comment by tim77** [comment]
I like this new one and it's better fit into new GNOME icons family. But old one is nice too.

**Comment by Fatih20** [comment]
> But old one is nice too.
I'd have to disagree.

**Comment by ElXreno** [comment]
I prefer the old icon rather than the new one.

**Comment by tim77** [comment]
New one is looks better in low res, old one looks better in high res. New one have canonical color palette for GNOME icons (`ed333b`). Really hard choice. Ideally i want to have version for low res and high res and if can add something sweet to high res version of new icon?

**Comment by amikha1lov** [comment]
@Fatih20 hi. how do you like this option?

**Comment by SeaDve** [comment]
#### I made a couple of modifications to make it more fitting in  GNOME DE.

image





#### This one is another option, I make it similar to GNOME Screenshot.

image

**Comment by tim77** [comment]
Just now noticed [this](https://github.com/amikha1lov/RecApp/pull/38#issuecomment-770200836) proposal and i like both. Awesome. I would say first variant is close to what @Fatih20 suggested from the beggining but with some sweeties and fit new GNOME icon guidelines.

I propose to pick new one for coming new RecApp v2.0. First variant since second already used in `Kooha`.

**Pull request closed without merging**
