### PR TITLE
UI redesign

### PR DESCRIPTION
**Pull request by SeaDve**
> 

First, thanks for this wonderful app, I have been using it in Fedora for almost a month now, very helpful. The only problem is that it seems not consistent with other GNOME apps.

I recreated this icon to match GNOME human interface guidelines. I also made a couple of mock-ups to make it more at home in GNOME (The SVG file is in the source code). If I have time soon, I'll create a pull request with the design changes.

mockup

Thanks! Would love to know your opinion.

### CODE REVIEW

**Comment by amikha1lov** [comment]
Thank you very much for your attention to the project and for your positive assessment. I really like your design, you did a great job. Thank you! I want to change the design in version 2.0. Unfortunately, for almost half a year I could not deal with the application due to a job change, but now I can devote time to it. First, I would like to solve the technical problems that have accumulated in the errors section, but then I will gladly change the design to your version.

If the opportunity presents itself, I will be very grateful to pr with the redesign.

Thanks again for a great job!

**Comment by amikha1lov** [comment]
just yesterday we tried to do something similar
https://i.imgur.com/4KM1laV.png

**Comment by SeaDve** [comment]
Thanks for the feedback!

I also modified a bit of the mock-up to change the labels, and add the pause screen and ability to record from microphone (possibly new feature? Should I open an issue?).

> just yesterday we tried to do something similar
> https://i.imgur.com/4KM1laV.png

BTW, I also check this, nice design! Is it already the actual app (coded) or still a mock-up?

**Comment by Latesil** [comment]
@SeaDve Thanks for great mock-up! it looks really nice. I have only 2 remarks: 
1. In my opinion, long text needs much more space between title above it. For example letter "g" in "Recording" is too close to title below.
2. I understand that three dots in "Recording" label mean a continuing process, but for me it visually move entire title to the left but I suppose it needs to be in the center. Maybe we should try to remove that dots?

**Comment by SeaDve** [comment]
>     1. In my opinion, long text needs much more space between title above it. For example letter "g" in "Recording" is too close to title below.

Do you mean this? 
image
If yes, I noticed it too. Actually, it was a lot closer on the first mock-up and I didn't realize it is still that close.


>     2. I understand that three dots in "Recording" label mean a continuing process, but for me it visually move entire title to the left but I suppose it needs to be in the center. Maybe we should try to remove that dots?

Had been discussing with myself about this, I think you're right. I'll also try to think of another way to show the continuing process (other than the big icon and the red button)

I will make new mock-ups about your remarks. I'll try to post them soon. Currently, I'm pretty busy with school works.

Thanks for the feedback!

**Comment by Latesil** [comment]
Nice, I think second option with "Recording" much better.

**Comment by SeaDve** [comment]
> Nice, I think second option with "Recording" much better.

Okay, updated the first screenshot.

**Comment by liferooter** [comment]
Does menu button open preferences or menu popover? If it opens preferences, I think it's better to use corresponding icon for button. If it opens menu, which options are there in this menu?

**Comment by liferooter** [comment]
Don't you think it will be better to use symbolic icons for start/stop buttons instead of text? I think it will look better if both stop and pause buttons will be symbolic.

**Comment by amikha1lov** [comment]
Maybe, it`s worth deleting the label with a path to the file, because some people don`t want to show their username

**Comment by amikha1lov** [comment]
i want to implement pause option, but I am not sure about it because I don't know if gstreamer is able to do it.

**Comment by SeaDve** [comment]
> Maybe, its worth deleting the label with a path to the file, because some people dont want to show their username

Here, what do you think about it.

image


> i want to implement pause option, but I am not sure about it because I don't know if gstreamer is able to do it.

I see, but I think it will be a good thing to implement in the future.

By the way, is it possible to build it using GNOME Builder? I tried to, but it's giving me this error.

```
WARNING: Could not detect glib version, assuming 2.54. You may get build errors if your glib is older.

../../../../../../../../../Projects/RecApp-master/src/meson.build:5:6: ERROR: Could not execute glib-compile-resources.
```
Sorry if this might be a dumb question, I am still learning gtk.

**Comment by amikha1lov** [comment]
i was able to implement pause function literally 5 minutes ago in a test project

**Comment by SeaDve** [comment]
Nice!
How do you test your commits? I am having trouble on building the package
with my commits.

**Comment by SeaDve** [comment]
image

I am able to make the mockups real but this doesn't have any function yet since I wasn't able to build from the main branch.

**Comment by amikha1lov** [comment]
> image
> 
> 
> I also just made the mockups come to life, but this doesn't have any function yet since I wasn't able to build from the main branch.
> 
> I tried to keep it as consistent as the original screenshot app from GNOME.
> 

everything works for me, even after git clone.  how do you do it?  write in steps

**Comment by SeaDve** [comment]
I skipped the git clone since I already have it in my home folder, then:
1. cd RecApp
2. git submodule update --init --recursive #This is where it doesn't work

**Comment by amikha1lov** [comment]
Excellent, thanks

**Comment by amikha1lov** [comment]
> I skipped the git clone since I already have it in my home folder, then:
> 
> 1. cd RecApp-master
> 2. git submodule update --init --recursive #This is where it doesn't work
> 
> Btw, what do you think of the design? It took me hours to change the color and the border-radius, lol. I'll send the source code?

I'll ask @tim77 about submodules and write you after that

**Comment by tim77** [comment]
> I skipped the git clone since I already have it in my home folder, then:

> git submodule update --init --recursive #This is where it doesn't work

@SeaDve i guess you downloaded ZIP with sources. If so then there is no submodules in project and that's why you can't clone submodules. You should clone all project via git exactly how this described [here](https://github.com/amikha1lov/RecApp#flatpak).

**Comment by SeaDve** [comment]
> > I skipped the git clone since I already have it in my home folder, then:
> 
> > git submodule update --init --recursive #This is where it doesn't work
> 
> @SeaDve i guess you downloaded ZIP with sources. If so then there is no submodules in project and that's why you can't clone submodules. You should clone all project via git exactly how this described [here](https://github.com/amikha1lov/RecApp#flatpak).

Okay, thanks!

**Comment by SeaDve** [comment]
Added animation yay. I rewrote most of the code since I use Gtk.Stack instead of relying on set_visible property.

https://user-images.githubusercontent.com/64297935/105700392-c48db180-5f43-11eb-9a25-326a2e0dbe54.mp4

**Comment by amikha1lov** [comment]
> Added animation yay. I rewrote most of the code since I use Gtk.Stack instead of relying on set_visible property.
> 
>  Screencast.from.01-25-2021.07.24.28.PM.mp4

it`s magnificently. Can i see source code ? I rewrote rec.py completely yesterday, now i use GstElementFactory for create pipeline.This allowed to implement pause option.

**Comment by SeaDve** [comment]
https://github.com/SeaDve/footage-design
(I only uploaded the modified files)

Here, I still have to clean the code (replace the toggle button with radio button, since toggle button is pretty buggy). Add the preferences.ui for preferences/settings and fix the css to support white theme.

**Comment by SeaDve** [comment]
image
Preferences button is now working

**Comment by SeaDve** [comment]
image
image

Transitioned AboutDialog to use .ui file

**Comment by SeaDve** [comment]
I'll make a new pull request to keep it clean. I guess it's ready, only a few bugs left.

**Comment by SeaDve** [comment]
I'll make a new pull request to keep it clean. I guess it's ready, only a few bugs left.

**Comment by amikha1lov** [comment]
@SeaDve  I am migrating the code from the master branch to the dev branch, so it is better to direct pr there

**Comment by SeaDve** [comment]
> @SeaDve I am migrating the code from the master branch to the dev branch, so it is better to direct pr there

Is there any different changes from the master? I already try to rename the elements to match the codebase.

**Comment by amikha1lov** [comment]
> Is there any different changes from the master? I already try to rename the elements to match the codebase.

I didn't any changes in widgets name

**Comment by SeaDve** [comment]
I build it and didn't give me errors, but it seems like it is not building from the local repo? Instead, it builds with the old files? These are steps of what I did.

(I'm already on folder RecApp)
git submodule update --init --recursive
mkdir -p $HOME/Projects/flatpak/repo
flatpak-builder --repo=$HOME/Projects/flatpak/repo --force-clean --ccache build-dir com.github.amikha1lov.RecApp.yaml
flatpak remote-add --no-gpg-verify local-repo $HOME/Projects/flatpak/repo
flatpak install com.github.amikha1lov.RecApp

**Comment by amikha1lov** [comment]
> flatpak install com.github.amikha1lov.RecApp

did you use flatpak update com.github.amikha1lov.RecApp command? do you build through the terminal or Gnome Builder ?

**Comment by SeaDve** [comment]
No, I didn't use flatpak update. Yes, I use builder's terminal.

**Comment by amikha1lov** [comment]
@SeaDve did it helped you? (flatpak update com.github.amikha1lov.RecApp)

**Comment by SeaDve** [comment]
Oh sorry, I'm pretty busy with school works today. I'll try tomorrow.

**Comment by SeaDve** [comment]
> @SeaDve did it helped you? (flatpak update com.github.amikha1lov.RecApp)

It works, but it is still not working good, I still have to rename and use <signal> in the .UI file. Might take me a while. Although I have rewritten the preferences window to integrate to the main window to make it easier to migrate.

Here is what It looks like.

https://user-images.githubusercontent.com/64297935/106341574-b55a8b00-62d8-11eb-9904-99f9075d7efa.mp4

**Comment by SeaDve** [comment]
> Don't you think it will be better to use symbolic icons for start/stop buttons instead of text? I think it will look better if both stop and pause buttons will be symbolic.


I'll consider this in the future.

**Pull request closed without merging**
