### PR TITLE
UI Redesign

### PR DESCRIPTION
**Pull request by SeaDve**
It is still not perfect, but most of the features now work.

#### Not working yet:
* Pause and continue buttons
* Label of where to save the video
* Hide some parts of the app when on Wayland (This is already possible but won't add it until other bugs are gone)
* Capture mode buttons
* _delay_button
* Record computer sounds
* Open Folder button in notifications

#### Needs work:
* video_folder_button should only show the folder not the entire directory
* Fix the icons on capture mode button
* Code cleaning
* Use preferences window

#### Visual bugs:
* Adwaita white mode isn't working well (ListBox borders)
* The popover's corner in preferences are cut off

Screenshot from 2021-01-30 19-31-13
Screenshot from 2021-01-30 19-31-21
Screenshot from 2021-01-30 19-31-24
Screenshot from 2021-01-30 19-31-28

### CODE REVIEW

**Comment by SeaDve** [comment]
[These are btw the changes made to use style classes instead of css](https://github.com/amikha1lov/RecApp/pull/66/commits/4ebd72473985c5f6613e630d6e08b6aeaf9c3b04)

**Comment by SeaDve** [comment]
I am currently migrating it to  a preferences window, but I might need some help since I'm not sure which functions goes to which window.

**Comment by amikha1lov** [comment]
i`d want to use the libhandy for the project in the future. This could help us to solve the problems with visual bugs. i`ll save your design and write your name in the credits. You did excellent work. Thank you

**Comment by SeaDve** [comment]
> i'd want to use the libhandy for the project in the future. This could help us to solve the problems with visual bugs. i'll save your design and write your name in the credits. 


Would be a good idea, and maybe a gtk4 port too. 

Should I continue though working on moving some of the options to preferences window? If we really follow the GNOME HIG we may consider removing options, possible high quality and 60 fps by default?


> You did excellent work. Thank you

Thanks! You're welcome. While working on it, I also learned a lot about gtk.

**Comment by SeaDve** [comment]
> i'd want to use the libhandy for the project in the future. This could help us to solve the problems with visual bugs.

Maybe I'll start porting some of the widgets to libhandy next week.

**Comment by SeaDve** [comment]
Done porting to libhandy, the visual bugs are now fixed. I committed it on my seadve branch.

**Pull request merged**
