### PR TITLE
Remove xdg-user-dirs and xdg-utils dependencies

### PR DESCRIPTION
**Pull request by mathiascode**
As the title says.

@SeaDve Could you check if this change improves https://github.com/amikha1lov/RecApp/issues/67?

### CODE REVIEW

**Comment by SeaDve** [comment]
> As the title says.
> 
> @SeaDve Could you check if this change improves #67?

I think yes! It is much faster and so far it haven't failed.

**Comment by mathiascode** [comment]
Looks like it's exclusive to the Flatpak build. I'll investigate.

**Comment by mathiascode** [comment]
I was scratching my head on https://github.com/amikha1lov/RecApp/issues/67 for a while. Turns out it's a regression in xdg-desktop-portal. https://github.com/flatpak/xdg-desktop-portal/issues/545

**Comment by SeaDve** [comment]
I found a fix to this (not the desired solution)
I'll push it on my seadve branch

**Comment by SeaDve** [comment]
I realized that this could also cause issues when saving the video since we are storing the saving location directory. When you restart your pc, it will have different inode numbers and fail to save the recording.

**Pull request merged**
